### ISSUE TITLE
Issue with image/video alignment on Project/Post pages

### ISSUE THREAD

**Issue by WalterRobin** [afivos/gauthierroussilhe#12]
<img width="1216" alt="Screenshot 2019-03-18 at 16 16 04" src="https://user-images.githubusercontent.com/30924717/54545260-405a6280-4999-11e9-9822-58f1587223f1.png">
<img width="1109" alt="Screenshot 2019-03-18 at 16 16 18" src="https://user-images.githubusercontent.com/30924717/54545261-405a6280-4999-11e9-9103-165d0efc7e9b.png">
<img width="1173" alt="Screenshot 2019-03-18 at 16 16 35" src="https://user-images.githubusercontent.com/30924717/54545262-405a6280-4999-11e9-8aaa-e4bc88e9d034.png">

**Comment by afivos** [comment]
Fixed: f8a97a10e6e0cc109baf8759181a04e0d79f13bc
